export const USERS_MOCK = [
  {
    id: 1,
    name: 'Felipe Rodrigues',
    email: 'felipe.rodrigues@gmail.com',
    createdAt: '05 de Maio de 2021',
  },
  {
    id: 2,
    name: 'Clara Brancalhão',
    email: 'brancalhaoclara@gmail.com',
    createdAt: '04 de Abril de 2021',
  },
  {
    id: 3,
    name: 'Igor Yamamoto',
    email: 'yamamoto.igor@gmail.com',
    createdAt: '03 de Fevereiro de 2021',
  },
  {
    id: 4,
    name: 'Tatiana Ippólito',
    email: 'tatirodrigues41@gmail.com',
    createdAt: '25 de Fevereiro de 2021',
  },
  {
    id: 5,
    name: 'Vinicius Ribeiro',
    email: 'vinii.ribeiro@gmail.com',
    createdAt: '13 de Fevereiro de 2021',
  },
  {
    id: 6,
    name: 'Felipe Rodrigues',
    email: 'felipe.rodrigues@gmail.com',
    createdAt: '05 de Maio de 2021',
  },
  {
    id: 7,
    name: 'Clara Brancalhão',
    email: 'brancalhaoclara@gmail.com',
    createdAt: '04 de Abril de 2021',
  },
  {
    id: 8,
    name: 'Igor Yamamoto',
    email: 'yamamoto.igor@gmail.com',
    createdAt: '03 de Fevereiro de 2021',
  },
  {
    id: 9,
    name: 'Tatiana Ippólito',
    email: 'tatirodrigues41@gmail.com',
    createdAt: '25 de Fevereiro de 2021',
  },
  {
    id: 10,
    name: 'Vinicius Ribeiro',
    email: 'vinii.ribeiro@gmail.com',
    createdAt: '13 de Fevereiro de 2021',
  },
  {
    id: 11,
    name: 'Zezin',
    email: 'felipe.rodrigues@gmail.com',
    createdAt: '05 de Maio de 2021',
  },
  {
    id: 12,
    name: 'Clara Brancalhão',
    email: 'brancalhaoclara@gmail.com',
    createdAt: '04 de Abril de 2021',
  },
  {
    id: 13,
    name: 'Igor Yamamoto',
    email: 'yamamoto.igor@gmail.com',
    createdAt: '03 de Fevereiro de 2021',
  },
  {
    id: 14,
    name: 'Tatiana Ippólito',
    email: 'tatirodrigues41@gmail.com',
    createdAt: '25 de Fevereiro de 2021',
  },
  {
    id: 15,
    name: 'Vinicius Ribeiro',
    email: 'vinii.ribeiro@gmail.com',
    createdAt: '13 de Fevereiro de 2021',
  },
  {
    id: 16,
    name: 'Felipe Rodrigues',
    email: 'felipe.rodrigues@gmail.com',
    createdAt: '05 de Maio de 2021',
  },
  {
    id: 17,
    name: 'Clara Brancalhão',
    email: 'brancalhaoclara@gmail.com',
    createdAt: '04 de Abril de 2021',
  },
  {
    id: 18,
    name: 'Igor Yamamoto',
    email: 'yamamoto.igor@gmail.com',
    createdAt: '03 de Fevereiro de 2021',
  },
  {
    id: 19,
    name: 'Tatiana Ippólito',
    email: 'tatirodrigues41@gmail.com',
    createdAt: '25 de Fevereiro de 2021',
  },
  {
    id: 20,
    name: 'Ze Bonitin',
    email: 'vinii.ribeiro@gmail.com',
    createdAt: '13 de Fevereiro de 2021',
  },
  {
    id: 21,
    name: 'Felipe Rodrigues',
    email: 'felipe.rodrigues@gmail.com',
    createdAt: '05 de Maio de 2021',
  },
  {
    id: 22,
    name: 'Clara Brancalhão',
    email: 'brancalhaoclara@gmail.com',
    createdAt: '04 de Abril de 2021',
  },
  {
    id: 23,
    name: 'Igor Yamamoto',
    email: 'yamamoto.igor@gmail.com',
    createdAt: '03 de Fevereiro de 2021',
  },
  {
    id: 24,
    name: 'Tatiana Ippólito',
    email: 'tatirodrigues41@gmail.com',
    createdAt: '25 de Fevereiro de 2021',
  },
  {
    id: 25,
    name: 'Vinicius Ribeiro',
    email: 'vinii.ribeiro@gmail.com',
    createdAt: '13 de Fevereiro de 2021',
  },
  {
    id: 26,
    name: 'Felipe Rodrigues',
    email: 'felipe.rodrigues@gmail.com',
    createdAt: '05 de Maio de 2021',
  },
  {
    id: 27,
    name: 'Clara Brancalhão',
    email: 'brancalhaoclara@gmail.com',
    createdAt: '04 de Abril de 2021',
  },
  {
    id: 28,
    name: 'Igor Yamamoto',
    email: 'yamamoto.igor@gmail.com',
    createdAt: '03 de Fevereiro de 2021',
  },
  {
    id: 29,
    name: 'Tatiana Ippólito',
    email: 'tatirodrigues41@gmail.com',
    createdAt: '25 de Fevereiro de 2021',
  },
  {
    id: 30,
    name: 'Vinicius Ribeiro',
    email: 'vinii.ribeiro@gmail.com',
    createdAt: '13 de Fevereiro de 2021',
  },
  {
    id: 31,
    name: 'Felipe Rodrigues',
    email: 'felipe.rodrigues@gmail.com',
    createdAt: '05 de Maio de 2021',
  },
  {
    id: 32,
    name: 'Clara Brancalhão',
    email: 'brancalhaoclara@gmail.com',
    createdAt: '04 de Abril de 2021',
  },
  {
    id: 33,
    name: 'Igor Yamamoto',
    email: 'yamamoto.igor@gmail.com',
    createdAt: '03 de Fevereiro de 2021',
  },
  {
    id: 34,
    name: 'Tatiana Ippólito',
    email: 'tatirodrigues41@gmail.com',
    createdAt: '25 de Fevereiro de 2021',
  },
  {
    id: 35,
    name: 'Vinicius Ribeiro',
    email: 'vinii.ribeiro@gmail.com',
    createdAt: '13 de Fevereiro de 2021',
  },
  {
    id: 36,
    name: 'Felipe Rodrigues',
    email: 'felipe.rodrigues@gmail.com',
    createdAt: '05 de Maio de 2021',
  },
  {
    id: 37,
    name: 'Clara Brancalhão',
    email: 'brancalhaoclara@gmail.com',
    createdAt: '04 de Abril de 2021',
  },
  {
    id: 38,
    name: 'Igor Yamamoto',
    email: 'yamamoto.igor@gmail.com',
    createdAt: '03 de Fevereiro de 2021',
  },
  {
    id: 39,
    name: 'Tatiana Ippólito',
    email: 'tatirodrigues41@gmail.com',
    createdAt: '25 de Fevereiro de 2021',
  },
  {
    id: 40,
    name: 'Vinicius Ribeiro',
    email: 'vinii.ribeiro@gmail.com',
    createdAt: '13 de Fevereiro de 2021',
  },
  {
    id: 41,
    name: 'Felipe Rodrigues',
    email: 'felipe.rodrigues@gmail.com',
    createdAt: '05 de Maio de 2021',
  },
  {
    id: 42,
    name: 'Clara Brancalhão',
    email: 'brancalhaoclara@gmail.com',
    createdAt: '04 de Abril de 2021',
  },
  {
    id: 43,
    name: 'Igor Yamamoto',
    email: 'yamamoto.igor@gmail.com',
    createdAt: '03 de Fevereiro de 2021',
  },
  {
    id: 44,
    name: 'Tatiana Ippólito',
    email: 'tatirodrigues41@gmail.com',
    createdAt: '25 de Fevereiro de 2021',
  },
  {
    id: 45,
    name: 'Vinicius Ribeiro',
    email: 'vinii.ribeiro@gmail.com',
    createdAt: '13 de Fevereiro de 2021',
  },
]
